[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entity = { path = "../entity" }
axum = "0.6.7"
tokio = { version = "1.25.0", features = ["full"] }
dotenv = "0.15.0"
async-graphql-axum = "5.0.6"
